### ISSUE TITLE
Keep checkbox present if successful upload took place

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#281] opened 2017-06-02 02:47 UTC
to reproduce, try to upload 10+ images to OpenOversight in production.

**Comment by freddymartinez9** [comment] 2017-06-02 15:39
![out](https://cloud.githubusercontent.com/assets/3100220/26733180/a503c8de-477f-11e7-84de-0202c9529947.gif)

**Comment by redshiftzero** [comment] 2017-06-03 03:05
This looks like a duplicate of #280... ?

So clicking the X 1) will never do anything and 2) the image is not removed and doesn't need to be because it has not been uploaded. If you successfully upload an image then a checkmark will appear briefly and disappear, if an issue occurred - e.g. the image has already been uploaded - then the X will appear letting you know it was not uploaded and the reason why it was not uploaded will appear upon hover. 

Unless there's more to this, everything is working as intended in production and we should instead open a UX issue to pin down the usability issues here if the behavior here is unintuitive.

**Comment by redshiftzero** [comment] 2017-06-03 03:21
Converted this to a UX ticket. If we want to move forward on this ideally one would do some user testing to determine what would make this more usable. However, as a stopgap, a brief explanation on the upload page briefly describing "If you successfully upload an image then a checkmark will appear briefly and disappear, if an issue occurred - e.g. the image has already been uploaded - then the X will appear letting you know it was not uploaded and the reason why it was not uploaded will appear upon hover." in more understandable terms would be helpful.

**Comment by redshiftzero** [comment] 2018-04-23 04:26
So when users first use the upload, the confusing part to them is that they miss the checkbox flashing up and think they need to do something else to add more photos. A reasonable thing to do here would be to make the checkbox _not_ disappear upon upload.

**Comment by redshiftzero** [comment] 2018-04-23 04:30
Ah.. closing as duplicate of #373

**Closed by redshiftzero** 2018-04-23 04:30 UTC
Labels: good first issue, ux/ui
