### ISSUE TITLE
Do not allow browse/find for departments without officers

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#491] opened 2018-07-08 22:10 UTC
Right now in order to accept submissions from the public for ICE, CBP, and NYPD, we added them to OpenOversight which by default enables the departments to be listed on the Browse page (https://openoversight.com/browse) even though there are no officers yet (we don't have the rosters).

We should not show them on the browse page until we have the roster. In addition, we should not show them in the dropdown field in step 1 of the find an officer page:

<img width="1135" alt="screen shot 2018-07-08 at 3 09 33 pm" src="https://user-images.githubusercontent.com/7832803/42424413-f14a32f0-82c0-11e8-9f7e-57458bac5642.png">

**Comment by bmintz** [comment] 2018-07-25 00:14
OK I'll take on this issue. I cannot reproduce it though. I see officers in every department on https://lucyparsons.com/browse, and there's no dropdown either.

**Comment by redshiftzero** [comment] 2018-07-25 20:42
Ah yep, since I filed this issue, there is now each least one officer for each department. In terms of reproducing this, you can add a new department (without officers) in the development environment through the web application by:

 1. Login as the test user: user `test@example.org`, password `testtest`
 2. Go to `volunteer`
 3. Scroll down to Add New Department:

<img width="378" alt="screen shot 2018-07-25 at 1 42 18 pm" src="https://user-images.githubusercontent.com/7832803/43226379-920b5352-9010-11e8-80ff-2f636b76b213.png">

Then when you go "Browse" the department will appear even though there are no officers.

**Comment by abandoned-prototype** [comment] 2018-07-30 12:08
sorry @bmintz, I am new to github, so I decided to play around with some smaller fixes in my forked repository to get used to it, not realizing that those would be automatically referenced here.
Please disregard the above linked commit of mine.

**Comment by sibrahi5** [comment] 2019-01-29 19:55
This was fixed with #545 but never closed. Closing!

**Closed by sibrahi5** 2019-01-29 19:55 UTC
Labels: easy, good first issue, help wanted, size/S
