### ISSUE TITLE
Search for multiple races at once

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#277] opened 2017-05-27 19:14 UTC
This one is a bit tricky in terms of racial demographics

**Comment by redshiftzero** [comment] 2017-06-15 22:26
Hmm... why? Note that the race information comes straight from the rosters we get. On a related note, we should definitely be able to search by more than one race, e.g. a single search should be possible for both white AND hispanic officers. Currently you must select one. Would that address the issue here?

**Comment by redshiftzero** [comment] 2018-01-27 04:10
This is a dupe of #262

**Closed by redshiftzero** 2018-01-27 04:10 UTC
Labels: for tip consideration ($), size/S, tech/python
